### ISSUE TITLE
[Bug]: Unable to use `get_stadia` - endpoint error

### ISSUE THREAD

**Issue by pjsharpe07** [American-Soccer-Analysis/itscalledsoccer#176] opened 2024-06-26 18:46 UTC
### What happened?

Running something like `data = asa_client.get_stadia(leagues='mls')` yields `HTTPError: 404 Client Error: Not Found for url: https://app.americansocceranalysis.com/api/v1/nwsl/stadiums`.

Did a little digging and looks like `https://app.americansocceranalysis.com/api/v1/nwsl/stadia` is a valid endpoint though I didn't validate the data. Seems right though

### Version

0.2.0

### What version of Python are you using?

Python 3.10.x

### What operating system are you using?

Windows

**Comment by bgrnwd** [comment] 2024-06-27 01:16
@pjsharpe07 Can you try upgrading itscalledsoccer to the latest version (1.2.0)? It looks like you're on a rather old version. I was able to run your code sample just fine with a newer version

**Comment by bgrnwd** [comment] 2024-06-27 01:21
Actually I was able to reproduce the error with `1.2.0`. I think your PR will fix it so I will give that a review.

**Comment by bgrnwd** [comment] 2024-06-28 01:40
@pjsharpe07 This is fixed in `1.2.1`. Thanks again for the PR 🙇

**Closed by bgrnwd** 2024-06-28 01:40 UTC
Labels: bug
